<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.2.4 setup script
 * Date: Tue, 24 Jun 2014 16:10:37 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: docker mysql [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'docker mysql';
$cfg['Servers'][$i]['host'] = 'mysql';
$cfg['Servers'][$i]['port'] = '3306';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'DOCKER_RANDOM';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>
